config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  root 'home#index'
  get 'home/about'
  get 'home/lookup'
  post 'home/lookup' => 'home/lookup'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :crypto, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # only the correct user can edit, update, view, or destroy a thing
  before_action :correct_user, only: [:edit, :show, :update, :destroy]

  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @my_crypto = JSON.parse(@response)
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_crypto = JSON.parse(@response)
      for coin in @show_crypto
        if @crypto.symbol.upcase == coin['symbol']
          @crypto_name = coin['name']
          @crypto_1h = coin['percent_change_1h']
          @crypto_24h = coin['percent_change_24h']
          @crypto_7d = coin['percent_change_7d']
          @crypto_rank = coin['rank']
          @crypto_price = coin['price_usd']
          @crypto_price_btc = coin['price_btc']
          @crypto_24h_volume = coin['24h_volume_usd']
          @crypto_market_cap = coin['market_cap_usd']
          @crypto_available_supply = coin['available_supply']
          @crypto_max_supply = coin['max_supply']
        end
      end
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to cryptos_path, :flash => { :error => "Record not found." }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end

    def correct_user
      @correct = current_user.crypto.find_by(id: params[:id])
      redirect_to cryptos_path, notice: "You are not authorized to complete your request" if @correct.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
  end

  def about
  end

  def lookup
  require 'net/http'
  require 'json'
  @url = 'https://api.coinmarketcap.com/v1/ticker/'
  @uri = URI(@url)
  @response = Net::HTTP.get(@uri)
  @coins = JSON.parse(@response)
  @all_symbols = []
  @all_names = []
    for x in @coins
      @all_symbols << x['symbol']
      @all_names << x['name']
    end
  end
end

# <% @coins.each do |coin| %>
#    <% if coin["symbol"] == @symbol %>
#    <%= coin["name"] %>: $<%= coin["price_usd"] %>
#   <% end %>
# <% end %>
      # for coin in @coins
      #   if sym == coin["symbol"]
      #     puts "#{coin["name"]}: #{coin["price_usd"]}"
      #   end
      # end
#       <% @coins.each do |coin| %>
#   <% if coin["symbol"] == @symbol %>
#     <%= coin["name"] %>: $<%= coin["price_usd"] %>
#   <% end %>
# <% end %>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= simple_form_for(@crypto) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :symbol, :input_html => { :class => "symbol" } %>
    <%= f.number_field :user_id, value: current_user.id , type: "hidden", :input_html => { :class => "symbol" } %>
    <%= f.input :cost_per, type: Integer, :input_html => { :class => "symbol" } %>
    <%= f.input :amount_owned, :input_html => { :class => "symbol" } %>
  </div>

  <div class="form-actions" style="margin-top: 15px; margin-bottom: 5px;">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<% total_portfolio = 0 %>
<h1>Your cryptocurrencies</h1>
<br>
<table class="table table-striped table-bordered table-responsive table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Value (per unit)</th>
      <th>Purchased at (per unit)</th>
      <th>Quantity owned</th>
      <th>Total Amount Invested</th>
      <th>Current Investment Value</th>
      <th>Profit/Loss If Sold Now</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
      <% if crypto.user_id == current_user.id %>
        <% if crypto.symbol %>
          <% crypto.symbol = crypto.symbol.upcase %>
        <% end %>
        <tr>
        <% for coin in @my_crypto %>
           <% if crypto.symbol == coin['symbol'] %>
              <td><%= link_to coin['name'], crypto %></td>
              <td>$<%= coin['price_usd'] %></td>
              <td>$<%= crypto.cost_per %></td>
              <td><%= crypto.amount_owned %></td>
              <% @total_amount_invested = (crypto.cost_per * crypto.amount_owned) %>
              <td><%= number_to_currency(@total_amount_invested) %></td>
              <% @current_investment_value = (crypto.amount_owned.to_d * coin['price_usd'].to_d) %>
              <td><%= number_to_currency(@current_investment_value) %></td>
              <td><%= number_to_currency(@current_investment_value - @total_amount_invested) %></td>
              <% total_portfolio += (@current_investment_value - @total_amount_invested) %>
<!--           # elsif @crypto != "#{coin['symbol']}"
          #   @crypto  = "Sorry, could not retrieve records for your search. Please try again." -->
          <% end %>
        <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<% profit_or_loss = "loss" %>
<% if total_portfolio > 0 %>
  <% profit_or_loss = "profit" %>
<% end %>
<h3>Your portfolio has an overall <em><u><%= profit_or_loss %></u></em> of <%= number_to_currency(total_portfolio) %>.</h3>
<br>
<%= link_to 'Add a Crypto', new_crypto_path, class: "btn btn-primary"%>

app/views/cryptos/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Add a Cryptocurrency</h3>
  </div>

  <div class="body">
  <%= render 'form', crypto: @crypto %>

  <%= link_to 'Back', cryptos_path %>
  </div>
</div>

app/views/cryptos/show.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title"><%= @crypto_name %></h3>
  </div>

  <div class="panel-body">

      <p>
        <strong>Symbol:</strong>
        <%= @crypto.symbol.upcase %>
      </p>

      <p>
        <strong>CoinMarketCap Ranking:</strong>
        <%= @crypto_rank %>
      </p>

      <p>
        <strong>Current Price USD (per unit):</strong>
          <%= number_to_currency(@crypto_price) %>
      </p>

      <p>
        <strong>Current Price BTC (per unit):</strong>
        <%= @crypto_price_btc %>
      </p>

      <p>
        <strong>24hr Trading Volume:</strong>
          <%= number_to_currency(@crypto_24h_volume) %>
      </p>

      <p>
        <strong>1hr Change:</strong>
          <%= @crypto_1h %>%
      </p>

      <p>
        <strong>24hr Change:</strong>
          <%= @crypto_24h %>%
      </p>

      <p>
        <strong>7 Day Change:</strong>
          <%= @crypto_7d %>%
      </p>

      <p>
        <strong>Market Cap:</strong>
          <%= number_to_currency(@crypto_market_cap) %>
      </p>

      <p>
        <strong>Available Supply:</strong>
        <%= @crypto_available_supply %> <%= @crypto.symbol.upcase %>
      </p>

      <p>
        <strong>Max Supply:</strong>
        <%= @crypto_max_supply %> <%= @crypto.symbol.upcase %>
      </p>

      <p>
        <strong>Purchased at:</strong>
        <%= number_to_currency(@crypto.cost_per) %>
      </p>

      <p>
        <strong>Amount owned:</strong>
        <%= @crypto.amount_owned %>
      </p>

  </div>

  <div class="panel-footer">
    <%= link_to 'Edit', edit_crypto_path(@crypto) %> |
    <%= link_to 'Delete', @crypto, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'My Portfolio', cryptos_path %>
  </div>

</div>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "My Crypto Portfolio", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Top 100", root_path %></li>
<!--         <li><%= link_to "About Us", home_about_path %></li> -->
        <li><%= link_to "Search", home_lookup_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Portfolio", cryptos_path %></li>
          <li><%= link_to "Add a Crypto", new_crypto_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<!-- <h1>About Us</h1>
<p>I am the real Slim Shady</p> -->

app/views/home/index.html.erb
<h1>Top 100</h1><br>
<h3>The following are CoinMarketCap's Top 100 Cryptocurrencies:</h3><br>

<br><br>

<table class="table table-striped table-bordered table-responsive table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>CoinMarketCap Ranking</th>
      <th>Current Price</th>
      <th>7 Day Change</th>
      <th>24Hr Trading Volume</th>
      <th>Market Cap</th>
      <th>Add to my Portfolio</th>
    </tr>
  </thead>
  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin["name"] %></td>
        <td><%= coin["symbol"] %></td>
        <td><%= coin["rank"] %></td>
        <td><%= number_to_currency(coin["price_usd"]) %></td>
        <td><%= coin["percent_change_7d"] %>%</td>
        <td><%= number_to_currency(coin["24h_volume_usd"]) %></td>
        <td><%= number_to_currency(coin["market_cap_usd"]) %></td>
        <td><%= link_to "Add", new_crypto_path, symbol: coin["symbol"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/lookup.html.erb
<h3>Search for a Cryptocurrency</h3>
<br>

<%= form_tag home_lookup_path, :method => 'POST' do %>
  <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Name or Symbol', size: 50 %>
  <%= submit_tag 'Search', class: "btn btn-primary"%>
<% end %>
<br>

<% @symbol = params[:sym] %>
<% if @symbol %>
  <% if @symbol.upcase == "AMB" %>
    <%= "I suggest you revise your investment strategy" %>
  <% elsif (@symbol == "") || ((@all_symbols.exclude? @symbol.upcase) && (@all_names.exclude? @symbol.capitalize)) %>
    <div class="error">
    <%= "Error: Please enter a valid cryptocurrency name or symbol ('BTC', 'Bitcoin', etc.)." %>
    </div>
  <% end %>
  <% for coin in @coins %>
    <% if (@symbol.upcase == coin['symbol']) || (@symbol.capitalize == coin['name']) %>
      <table class="table table-striped table-bordered table-responsive table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Symbol</th>
            <th>CoinMarketCap Ranking</th>
            <th>Current Price</th>
            <th>7 Day Change</th>
            <th>24Hr Trading Volume</th>
            <th>Market Cap</th>
            <th>Add to my Portfolio</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= coin["name"] %></td>
              <td><%= coin["symbol"] %></td>
              <td><%= coin["rank"] %></td>
              <td><%= number_to_currency(coin["price_usd"]) %></td>
              <td><%= coin["percent_change_7d"] %>%</td>
              <td><%= number_to_currency(coin["24h_volume_usd"]) %></td>
              <td><%= number_to_currency(coin["market_cap_usd"]) %></td>
              <td><%= link_to "Add", new_crypto_path, symbol: coin["symbol"] %></td>
            </tr>
        </tbody>
      </table>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Crypto Portfolio</title>

    <meta name="description" content="Track your cryptocurrencies with ease.">
    <meta property="og:title" content="My Crypto Portfolio">
    <meta property="og:image" content="https://cdn.pixabay.com/photo/2017/12/26/21/43/blockchain-3041480_960_720.jpg">
    <meta property="og:type" content="website">
    <meta property="og:description" content="Track your cryptocurrencies with ease.">
    <meta property="og:site_name" content="My Crypto Portfolio">
    <meta property="og:url" content="<%= request.original_url %>" >
    <%= favicon_link_tag asset_path('icons8-bitcoin-16.png') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= render 'home/flash' %>
      <%= yield %>
    </div>
  </body>
</html>